### PR TITLE
Job vacancies with drill down

### PR DESCRIPTION
**Pull request by HartmannssonIQX**

### CODE REVIEW

**Comment by HartmannssonIQX** [comment]
Job vacancies with drill down.

**Comment by MichaelFHScott** [comment]
Hi Brynjar 
Please could you add the xml job to the pull request? It think you just need to commit it.
Should be jobs\uploadvacancies JSON.xml

**Comment by MichaelFHScott** [comment]
Specifically commit and push to HartmannssonIQX:Job_vacancies_2

**Comment by HartmannssonIQX** [comment]
I have pushed the updated xml job to the pull request.

 

 

Best regards,

Brynjar

01835 340062 (316)

**Pull request merged**
